### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by varaprasad7007** [CraigglesO/anki-to-json#1]
Hi, sir! I'm trying to download `npm install anki-to-json `, but I'm facing some errors and not installing the library. please help me out.

**Comment by CraigglesO** [comment]
Hello, sorry I just saw this. Can you provide some feedback on what you have tried?

Have you installed NodeJS? Which operating system do you use?

I haven't used this in over a year, but I just installed the package with no issues.

**Comment by isaacgannon** [comment]
Hey , I am running windows 10 I have node installed, and I have gone and installed all of the other dependencies listed on the npm website https://www.npmjs.com/package/anki-to-json

This is my debug log
[2021-09-05T03_31_05_720Z-debug.log](https://github.com/CraigglesO/anki-to-json/files/7110857/2021-09-05T03_31_05_720Z-debug.log)

**Comment by CraigglesO** [comment]
@isaacgannon - seems like it's not happy with the specific version of sqlite3? Hard to tell, but you're using node v14.17.4 and I'm pretty sure sqlite3 is picky on the node version.

Try:
```
npm install -g n
n 12
```

This will move you to node version 12. Should work in that case.
If you want to revert back to version 14 just type `n 14` or `n latest`

I use UNIX for programming though so your milage will vary.
