### ISSUE TITLE
Missing character

### ISSUE THREAD

**Issue by tranviet0710** [CraigglesO/anki-to-json#3]
The tool is so perfect <3. 
Btw the media URL exported doesn't have the first character of each image.

**Comment by tranviet0710** [comment]
Please help me fix it ^.^ Many thanks

**Comment by CraigglesO** [comment]
I just noticed this. Let me see if I can fix in the morning. Do you have a deck I can use to better understand the issue?

**Comment by tranviet0710** [comment]
Sure, how can I send you a demo deck? I just exported the apkg and everything is very good, except the url to the image in media:[]

**Comment by CraigglesO** [comment]
If you zip the deck you're trying to convert and drag it into the comment it should work no problem. You may not even need to zip it, you can just drag it into the comment and submit.

**Comment by tranviet0710** [comment]
Just like this DEMO DECK bro, has back part includes: the meaning of word and describe image, the URL of image exported is missing the first character. 

[DEMO DECK.zip](https://github.com/CraigglesO/anki-to-json/files/9557458/DEMO.DECK.zip)

**Comment by CraigglesO** [comment]
Fixed. I incremented the npm package as well as update the repo. Should work now. Includes the image file type as well now. Let me know if you run into any other issues!

**Comment by tranviet0710** [comment]
![image](https://user-images.githubusercontent.com/79961919/190043014-2aee67b7-b42f-4097-a44e-6c995cd846db.png)
It keeps getting this error and i dont get any json file.

**Comment by CraigglesO** [comment]
what version on nodeJS are you using? Can you upgrade?
```shell
npm i -g n
n latest
```

**Comment by tranviet0710** [comment]
If I use Nodejs. it is great ^^ Many thanks bro
Btw if I use Bin, it keeps gettings this exception :((
![image](https://user-images.githubusercontent.com/79961919/190191427-fe8393b2-fbdc-4893-83a1-385b11219bfe.png)
